name: flutter_instaclone
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.3+3
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.7
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  flutter_pw_validator: ^1.2.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.5.1
  device_info: ^2.0.2
  firebase_messaging: ^10.0.6
  flutter_local_notifications: ^8.1.1+2
  share: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
